# faraday-deamon configuration
# This file configures the MySQL proxies that faraday-deamon should manage

proxies:
  - proxy_name: "mysql_proxy_1"
    listen_port: 3307
    target_host: "localhost"
    target_port: 3306
    buffer_size: 1000
    log_level: "INFO"
  
  - proxy_name: "mysql_proxy_2"
    listen_port: 3309  # 修改为未被占用的端口
    target_host: "localhost"
    target_port: 3306
    buffer_size: 1000
    log_level: "INFO"

# Deamon configuration
daemon:
  log_file: "/var/log/faraday-deamon.log"
  pid_file: "/var/run/faraday-deamon.pid"

# Kafka configuration (optional)
# kafka:
  # Kafka broker addresses
#   brokers:
#     - "localhost:9092"
  # Topic to send MySQL query logs
#   topic: "mysql_queries"